### ISSUE TITLE
Process Ngnk exited abnormally with code 126

### ISSUE THREAD

**Issue by hoosierEE** [gitonthescene/ngnk-mode#1]
`ngnk-cli-file-path` seems to have picked up the right path but I get `Process Ngnk exited abnormally with code 126` when I use `M-x run-ngnk`.

Could the problem be that my "k" executable is actually this script:

```
rlwrap ~/repo/k/k ~/repo/k/repl.k
```

?

**Comment by gitonthescene** [comment]
I’m traveling at the moment but will have a look when I get back.  FWIW, you don’t need either `rlwrap` nor `repl.k` on the command line as both are effectively picked up by the mode.  It’s probably better to point directly to the executable anyway.

**Comment by gitonthescene** [comment]
Thinking about it I think using `rlwrap` as an executable should be discouraged.  If you get errors when pointing to the executable directly feel free to reopen this issue, but I’ll close it for now.
